"""Drop unigue for post title

Revision ID: 0ff2bb5f7c7e
Revises: 8cf6b27d821c
Create Date: 2024-02-17 17:02:11.168721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff2bb5f7c7e'
down_revision: Union[str, None] = '8cf6b27d821c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_title_key', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_title_key', 'post', ['title'])
    # ### end Alembic commands ###
